### ISSUE TITLE
rangular print-outs

### ISSUE THREAD

**Issue by cffischer** [cffischer/Project-6#1]
Make an old version of rangular that prints out a lot of information from the following:
1) copy lodcsl.f90 and lodcsh2.f90 from the library to rangular_old
2) Make sure every line of code that writes to '(99, ' is executed (remove conditionals or !)
Modify the Makefile with a new name for executable such as "rangular_old"

This will be much more convenient than setting debug parameters.

**Comment by physicsfan** [comment]
### rangular90_old

(I've transferred this comment from Issue: Structure of the rangular program)
I now have "rangular90_old" running where much more information is printed to the screen, and the values of the T and V matrices are printed to a file "genmcp.dbg".  To get this to work, many steps had to be followed. I first moved the functions "lodcsl" and "lodcsh" from "lib9290" to "rangular". I then located all the unit=99 "write" statements that occur in "rangular"  These occur in routines: "lodcsl", "mcp_gg", "outsda", "sort" and "sortmem".  In "rangular", unit 99 is used for debugging purposed, it gets associated with a .dbg file whre all the debugging information is printed.  In the "rangular" main program, "genmcp", the second subroutine is "setdbg" which controls whether there will be debugging information generated.  Initially, this routine was disabled, returning control back to "genmcp" without performing any tasks. This feature, a "return" statement at the top of the routine was removed.  

Next, it was discovered that the debugging option was controlled by flag called NDEF, that was set initially at the beginning of "genmcp".  This flag is set when the user is asked if they want a "Full interaction?" or not.  the logic of the code is that if the user selects "yes", NDEF=0 and debugging information would not be generated. I initially experimented with this first conditional, explicitly changing the value of NDEF to instantiate debugging, but that ended up causing problems downstream. I expect that NDEF is used for more then just debugging.  The solution I decided on was to change the value of NDEF temporarily inside "setdbg" from 0 to 1, in order to initialize the debugging process, then to change it back to its original value (0) just before the "return" statement.  this allows the calculation to continue without problems but debugging is initiallized.

The final task that nedded to be performed was to augment the script files appropriately to allow for debugging.  When debugging is used, several questions are asked of the user as to what information is printed to file.  Of particular interest to us are the T and V coefficients.  I chose to print everything. so I added the needed number of 'y's to answer yes yo all the questions in the scripts.

For testing I've been using "example_1" and "case_1", where example_1 is Li and case_1 is "Mg" sequence.  I'm including the new output files and .dbg files for Li and Mg in the /local/asenchuk/share directory.

**Comment by cffischer** [comment]
# Rangular.f90 main program

This is much better.

  1. We need to settle on a style  -- maybe like SPHF?  I believe in headers  -- you have *** but maybe === is better.  The across the page double lines are too distracting. We have not discussed documentation but that will require some notation as well.  For the time being, we should omit === lines in the routine.

2.  You have failed to notice that many programs (including GRASP) need to run some code to initialize certain data, or setup up some procedure such as measuring time.  In particular, unless we figure out something better, GRASP needs to "CALL FACT" to set up a table of factorials.  A better choice would be "Call Initialize" that does a number of things to get the calculation started, like. Similarly, we could end with at "Call finish" to do whatever clean-up is needed like closing files and printing timing information.

3.  You omitted the very important  Call load_csfs for a series of blocks.

4.  But why do you need any of the USE modules?  There are no variables in your main program.  What is being used that is defined in the module?   When is a "USE module ever needed?  Thknk about it!

**Comment by cffischer** [comment]
#  Rangulr90.f90 continued

I forgot to mention, every Main program should declare what the program does.  Then there is the GRASP style that, for RANGULAR prints the heading

 RANGULAR
 This program performs angular integration
    Input file:  rcsf.inp
    Outputfiles: mcp.30, mcp.31, ....    rangular.log

Of course, out output files will be different.
